### ISSUE TITLE
out of memory in train  

### ISSUE THREAD

**Issue by OmarHamdoun** [mathformoso/Yolo-on-vedai#1]
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

2019-05-08 02:00:16.856460: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-05-08 02:00:17.832097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-05-08 02:00:17.837045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-08 02:00:18.342226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-08 02:00:18.345419: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-05-08 02:00:18.347379: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-05-08 02:00:18.349690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4716 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
box coords:
[[  61.242508   35.043827  782.1991    697.9861  ]
 [ 631.16266   138.7501   1123.5132    708.10925 ]
 [1198.9186    477.43094  1288.7426    687.31683 ]
 [ 628.6877    466.23425   732.0095    732.94244 ]]
******************************
scores:
[0.9987197  0.9986519  0.99211645 0.45523423]
******************************
labels:
[0 0 0 0]

(tracking_pytorch) D:\source_code\YOLOv3_TensorFlow>cd ..\Yolo-on-vedai

(tracking_pytorch) D:\source_code\Yolo-on-vedai>python train.py

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From train.py:140: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.map_and_batch(...)`.
WARNING:tensorflow:From train.py:139: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.

WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-08 02:08:04.326287: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-05-08 02:08:05.300810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-05-08 02:08:05.306172: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-08 02:08:05.817687: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-08 02:08:05.821336: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-05-08 02:08:05.823200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-05-08 02:08:05.825096: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6144 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-05-08 02:08:08.337421: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 6.00G (6442450944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-08 02:08:08.341564: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 5.40G (5798205440 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./data/darknet_weights/yolov3.ckpt

----------- start to train -----------

2019-05-08 02:08:31.102156: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-05-08 02:08:31.106547: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node yolov3/darknet53_body/Conv/Conv2D}}]]
         [[{{node add_29}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 233, in <module>
    feed_dict={is_training: True, handle_flag: train_handle_value})
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node yolov3/darknet53_body/Conv/Conv2D (defined at D:\source_code\Yolo-on-vedai\utils\layer_utils.py:21) ]]
         [[node add_29 (defined at D:\source_code\Yolo-on-vedai\model.py:282) ]]

Caused by op 'yolov3/darknet53_body/Conv/Conv2D', defined at:
  File "train.py", line 176, in <module>
    pred_feature_maps = yolo_model.forward(image, is_training=is_training)
  File "D:\source_code\Yolo-on-vedai\model.py", line 39, in forward
    route_1, route_2, route_3 = darknet53_body(inputs)
  File "D:\source_code\Yolo-on-vedai\utils\layer_utils.py", line 35, in darknet53_body
    net = conv2d(inputs, 32,  3, strides=1)
  File "D:\source_code\Yolo-on-vedai\utils\layer_utils.py", line 21, in conv2d
    padding=('SAME' if strides == 1 else 'VALID'))
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1155, in convolution2d
    conv_dims=2)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1058, in convolution
    outputs = layer.apply(inputs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\layers\base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 208, in __call__
    name=self.name)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node yolov3/darknet53_body/Conv/Conv2D (defined at D:\source_code\Yolo-on-vedai\utils\layer_utils.py:21) ]]
         [[node add_29 (defined at D:\source_code\Yolo-on-vedai\model.py:282) ]]

(tracking_pytorch) D:\source_code\Yolo-on-vedai>python train.py >>debug.txt
WARNING:tensorflow:From train.py:140: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.map_and_batch(...)`.
WARNING:tensorflow:From train.py:139: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.

WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-08 02:09:06.035432: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-05-08 02:09:07.056640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-05-08 02:09:07.062516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-08 02:09:07.581126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-08 02:09:07.584637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-05-08 02:09:07.586642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-05-08 02:09:07.588945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6144 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-05-08 02:09:10.212388: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 6.00G (6442450944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-08 02:09:10.216552: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 5.40G (5798205440 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./data/darknet_weights/yolov3.ckpt
2019-05-08 02:09:32.169896: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-05-08 02:11:43.951219: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node yolov3/darknet53_body/Conv/Conv2D}}]]
         [[{{node add_29}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 233, in <module>
    feed_dict={is_training: True, handle_flag: train_handle_value})
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node yolov3/darknet53_body/Conv/Conv2D (defined at D:\source_code\Yolo-on-vedai\utils\layer_utils.py:21) ]]
         [[node add_29 (defined at D:\source_code\Yolo-on-vedai\model.py:282) ]]

Caused by op 'yolov3/darknet53_body/Conv/Conv2D', defined at:
  File "train.py", line 176, in <module>
    pred_feature_maps = yolo_model.forward(image, is_training=is_training)
  File "D:\source_code\Yolo-on-vedai\model.py", line 39, in forward
    route_1, route_2, route_3 = darknet53_body(inputs)
  File "D:\source_code\Yolo-on-vedai\utils\layer_utils.py", line 35, in darknet53_body
    net = conv2d(inputs, 32,  3, strides=1)
  File "D:\source_code\Yolo-on-vedai\utils\layer_utils.py", line 21, in conv2d
    padding=('SAME' if strides == 1 else 'VALID'))
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1155, in convolution2d
    conv_dims=2)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1058, in convolution
    outputs = layer.apply(inputs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\layers\base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 208, in __call__
    name=self.name)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node yolov3/darknet53_body/Conv/Conv2D (defined at D:\source_code\Yolo-on-vedai\utils\layer_utils.py:21) ]]
         [[node add_29 (defined at D:\source_code\Yolo-on-vedai\model.py:282) ]]

**Comment by OmarHamdoun** [comment]
(tracking_pytorch) D:\source_code\Yolo-on-vedai>python train.py >>debug.txt
WARNING:tensorflow:From train.py:140: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.map_and_batch(...)`.
WARNING:tensorflow:From train.py:139: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, use
    tf.py_function, which takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.

WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py:1419: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-08 02:09:06.035432: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-05-08 02:09:07.056640: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1060 major: 6 minor: 1 memoryClockRate(GHz): 1.6705
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 4.97GiB
2019-05-08 02:09:07.062516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-08 02:09:07.581126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-08 02:09:07.584637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-05-08 02:09:07.586642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-05-08 02:09:07.588945: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6144 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-05-08 02:09:10.212388: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 6.00G (6442450944 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-05-08 02:09:10.216552: E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 5.40G (5798205440 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
WARNING:tensorflow:From C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\training\saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from ./data/darknet_weights/yolov3.ckpt
2019-05-08 02:09:32.169896: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-05-08 02:11:43.951219: E tensorflow/stream_executor/cuda/cuda_dnn.cc:334] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
Traceback (most recent call last):
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node yolov3/darknet53_body/Conv/Conv2D}}]]
         [[{{node add_29}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 233, in <module>
    feed_dict={is_training: True, handle_flag: train_handle_value})
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node yolov3/darknet53_body/Conv/Conv2D (defined at D:\source_code\Yolo-on-vedai\utils\layer_utils.py:21) ]]
         [[node add_29 (defined at D:\source_code\Yolo-on-vedai\model.py:282) ]]

Caused by op 'yolov3/darknet53_body/Conv/Conv2D', defined at:
  File "train.py", line 176, in <module>
    pred_feature_maps = yolo_model.forward(image, is_training=is_training)
  File "D:\source_code\Yolo-on-vedai\model.py", line 39, in forward
    route_1, route_2, route_3 = darknet53_body(inputs)
  File "D:\source_code\Yolo-on-vedai\utils\layer_utils.py", line 35, in darknet53_body
    net = conv2d(inputs, 32,  3, strides=1)
  File "D:\source_code\Yolo-on-vedai\utils\layer_utils.py", line 21, in conv2d
    padding=('SAME' if strides == 1 else 'VALID'))
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1155, in convolution2d
    conv_dims=2)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1058, in convolution
    outputs = layer.apply(inputs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1227, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\layers\base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 208, in __call__
    name=self.name)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\Omar\Anaconda3\envs\tracking_pytorch\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node yolov3/darknet53_body/Conv/Conv2D (defined at D:\source_code\Yolo-on-vedai\utils\layer_utils.py:21) ]]
         [[node add_29 (defined at D:\source_code\Yolo-on-vedai\model.py:282) ]]
